#site variables
remote_theme: mmistakes/so-simple-theme
locale: "en-GB"
title: Lottie Clarke
description: Lottie Clarke's writing portfolio
logo: /images/AVATAR.png
url: https://breezytealy.github.io
read_time: true
words_per_minute: 200
mathjax: true
tag_archive_path: "/tags/#"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate


#footer variables
footer_links:
  - title: Twitter
    url: https://twitter.com/astronomnomy
    icon: fab fa-twitter-square
  - title: Tumblr
    url: https://astronomnomy.tumblr.com
    icon: fab fa-tumblr-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
